# Generated by Django 4.0.6 on 2022-09-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRoom',
            fields=[
                ('messageRoomId', models.BigAutoField(help_text='Message Room ID', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('lastMessageId', models.IntegerField(default=True)),
                ('lastReadMessageId', models.IntegerField(default=True)),
                ('messageRoomId', models.ForeignKey(db_column='messageRoomId', on_delete=django.db.models.deletion.CASCADE, related_name='MessageUserPost', to='message.messageroom')),
                ('targetUser', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='user.profile', to_field='username_id')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='MessageUserPost', to='user.profile', to_field='username_id')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.BigAutoField(help_text='Meesage ID', primary_key=True, serialize=False)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(null=True)),
                ('messageImage', models.ImageField(null=True, upload_to='%Y/%m/%d')),
                ('messageRoomId', models.ForeignKey(db_column='messageRoomId', on_delete=django.db.models.deletion.CASCADE, related_name='messagePost', to='message.messageroom')),
                ('writer', models.ForeignKey(db_column='writer', on_delete=django.db.models.deletion.CASCADE, related_name='messagePost', to='user.profile', to_field='username_id')),
            ],
        ),
    ]
