# Generated by Django 4.0.6 on 2022-10-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_follower_fromuser_alter_following_touser_and_more'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageuser',
            name='targetUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', to_field='username_id'),
        ),
    ]
