# Generated by Django 4.0.6 on 2022-09-23 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_column='username', default=False, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customName', models.CharField(db_column='customName', default='', max_length=50)),
                ('userImage', models.ImageField(default='\\default.png', upload_to='%Y/%m/%d')),
                ('userComment', models.TextField(default='', null=True)),
                ('username', models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='searchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(db_column='log', max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchLogPost', to='user.profile', to_field='username_id')),
            ],
        ),
        migrations.CreateModel(
            name='following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toUser', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='user.profile', to_field='username_id')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followingPost', to='user.profile', to_field='username_id')),
            ],
        ),
        migrations.CreateModel(
            name='follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromUser', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='user.profile', to_field='username_id')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followerPost', to='user.profile', to_field='username_id')),
            ],
        ),
    ]
