# Generated by Django 4.0.6 on 2022-10-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='fromUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', to_field='username_id'),
        ),
        migrations.AlterField(
            model_name='following',
            name='toUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile', to_field='username_id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userImage',
            field=models.ImageField(default='default.png', upload_to='%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_column='username', max_length=255, unique=True),
        ),
    ]
