# Generated by Django 4.0.6 on 2022-09-25 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('storyId', models.BigAutoField(help_text='Story ID', primary_key=True, serialize=False)),
                ('storyImage', models.ImageField(default='\\default.png', upload_to='%Y/%m/%d')),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='storyPost', to='user.profile', to_field='username_id')),
            ],
        ),
        migrations.CreateModel(
            name='StoryViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyId', models.ForeignKey(db_column='story_id', default=False, on_delete=django.db.models.deletion.CASCADE, related_name='storyViewerPost', to='posting.story')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyViewerPost', to='user.profile', to_field='username_id')),
            ],
        ),
        migrations.CreateModel(
            name='poster',
            fields=[
                ('posterId', models.BigAutoField(help_text='Poster ID', primary_key=True, serialize=False)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='posterPost', to='user.profile', to_field='username_id')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('likeId', models.BigAutoField(help_text='Like ID', primary_key=True, serialize=False)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('liker', models.ForeignKey(db_column='liker', on_delete=django.db.models.deletion.CASCADE, related_name='likePost', to='user.profile', to_field='username_id')),
                ('posterId', models.ForeignKey(db_column='posterId', on_delete=django.db.models.deletion.CASCADE, related_name='likePost', to='posting.poster')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageId', models.BigAutoField(help_text='Poster Image ID', primary_key=True, serialize=False)),
                ('Oneimage', models.ImageField(default='media\\default.png', upload_to='%Y/%m/%d')),
                ('posterId', models.ForeignKey(db_column='posterId', on_delete=django.db.models.deletion.CASCADE, related_name='imagePost', to='posting.poster')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.BigAutoField(help_text='Comment ID', primary_key=True, serialize=False)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('posterId', models.ForeignKey(db_column='posterId', on_delete=django.db.models.deletion.CASCADE, related_name='commentPost', to='posting.poster')),
                ('writer', models.ForeignKey(db_column='writer', on_delete=django.db.models.deletion.CASCADE, related_name='commentPost', to='user.profile', to_field='username_id')),
            ],
        ),
    ]
