# Generated by Django 4.0.6 on 2022-10-10 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyviewer',
            name='viewerImage',
            field=models.ImageField(default='\\default.png', upload_to='%Y/%m/%d'),
        ),
    ]
