# Generated by Django 4.0.6 on 2022-10-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_storyviewer_viewerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storyviewer',
            name='viewerImage',
        ),
    ]
